version: "3"
services:

  datastore:
    platform: linux/arm64/v8
    image: busybox
    volumes:
        - /opt/datastore:/var/lib/mysql
    command: [/bin/sh]

  db:
    platform: linux/x86_64
    image: mysql:5.6
    container_name: mysql
    ports:
      - '3306:3306'
    volumes_from:
      - datastore
    environment:
      MYSQL_DATABASE: bbs
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    platform: linux/x86_64
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      # - PMA_USER=root
      # - PMA_PASSWORD=root
    ports:
      - "1000:80"

  php:
    platform: linux/arm64/v8
    image: php:7.4-fpm
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on: ["db"]

  nginx:
    platform: linux/arm64/v8
    image: nginx:latest
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/usr/share/nginx/html
    restart: always
    ports: ["8080:80"]
    depends_on: ["php"]
